name: Terminal-Executor-Publisher

on:
  pull_request:
    branches:
      - main
  release:
    types: [created]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  getVersion:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.create-environment-variables.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BUILD_TOKEN_2 }}
      - name: Generate env vars
        id: create-environment-variables
        run: |
          echo "version=$(${{github.workspace}}/gradlew -q getVersionName)" >> $GITHUB_OUTPUT

  build:
    permissions: write-all
    strategy:
      matrix:
        platform: [macos]
        include:
          - platform: macos
            runsOn: macos-latest
            zipCommand: 'tar -czf TerminalExecutor-Macos-Not-Notarized.tar.gz -C composeApp/build/compose/binaries/main-release/app .'
            archiveName: TerminalExecutor-Macos-Not-Notarized.tar.gz
    runs-on: ${{ matrix.runsOn }}
    needs: getVersion
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BUILD_TOKEN_2 }}

      - name: "Set up JDK for ${{ matrix.platform }}"
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'jetbrains'

      - name: "Build and run tests"
        if: matrix.platform == 'windows'
        run: |
          ./gradlew build

      - name: "Build v${{ needs.getVersion.outputs.version }} app for ${{ matrix.platform }}"
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          ./gradlew createReleaseDistributable
          ${{ matrix.zipCommand }}

      - name: Get Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Upload Release Asset v${{ needs.getVersion.outputs.version }} for ${{ matrix.platform }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.get_release.outputs.tag_name }} ./${{ matrix.archiveName }}
